export const countries = [
    { code: "+1", name: "United States", flag: "🇺🇸" },
    { code: "+93", name: "Afghanistan", flag: "🇦🇫" },
    { code: "+355", name: "Albania", flag: "🇦🇱" },
    { code: "+213", name: "Algeria", flag: "🇩🇿" },
    { code: "+376", name: "Andorra", flag: "🇦🇩" },
    { code: "+244", name: "Angola", flag: "🇦🇴" },
    { code: "+54", name: "Argentina", flag: "🇦🇷" },
    { code: "+374", name: "Armenia", flag: "🇦🇲" },
    { code: "+61", name: "Australia", flag: "🇦🇺" },
    { code: "+43", name: "Austria", flag: "🇦🇹" },
    { code: "+994", name: "Azerbaijan", flag: "🇦🇿" },
    { code: "+973", name: "Bahrain", flag: "🇧🇭" },
    { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
    { code: "+32", name: "Belgium", flag: "🇧🇪" },
    { code: "+55", name: "Brazil", flag: "🇧🇷" },
    { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
    { code: "+855", name: "Cambodia", flag: "🇰🇭" },
    { code: "+1", name: "Canada", flag: "🇨🇦" },
    { code: "+86", name: "China", flag: "🇨🇳" },
    { code: "+20", name: "Egypt", flag: "🇪🇬" },
    { code: "+33", name: "France", flag: "🇫🇷" },
    { code: "+49", name: "Germany", flag: "🇩🇪" },
    { code: "+30", name: "Greece", flag: "🇬🇷" },
    { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
    { code: "+36", name: "Hungary", flag: "🇭🇺" },
    { code: "+91", name: "India", flag: "🇮🇳" },
    { code: "+62", name: "Indonesia", flag: "🇮🇩" },
    { code: "+98", name: "Iran", flag: "🇮🇷" },
    { code: "+964", name: "Iraq", flag: "🇮🇶" },
    { code: "+353", name: "Ireland", flag: "🇮🇪" },
    { code: "+39", name: "Italy", flag: "🇮🇹" },
    { code: "+81", name: "Japan", flag: "🇯🇵" },
    { code: "+962", name: "Jordan", flag: "🇯🇴" },
    { code: "+254", name: "Kenya", flag: "🇰🇪" },
    { code: "+965", name: "Kuwait", flag: "🇰🇼" },
    { code: "+961", name: "Lebanon", flag: "🇱🇧" },
    { code: "+60", name: "Malaysia", flag: "🇲🇾" },
    { code: "+52", name: "Mexico", flag: "🇲🇽" },
    { code: "+212", name: "Morocco", flag: "🇲🇦" },
    { code: "+95", name: "Myanmar", flag: "🇲🇲" },
    { code: "+31", name: "Netherlands", flag: "🇳🇱" },
    { code: "+64", name: "New Zealand", flag: "🇳🇿" },
    { code: "+234", name: "Nigeria", flag: "🇳🇬" },
    { code: "+47", name: "Norway", flag: "🇳🇴" },
    { code: "+968", name: "Oman", flag: "🇴🇲" },
    { code: "+92", name: "Pakistan", flag: "🇵🇰" },
    { code: "+970", name: "Palestine", flag: "🇵🇸" },
    { code: "+63", name: "Philippines", flag: "🇵🇭" },
    { code: "+48", name: "Poland", flag: "🇵🇱" },
    { code: "+351", name: "Portugal", flag: "🇵🇹" },
    { code: "+974", name: "Qatar", flag: "🇶🇦" },
    { code: "+40", name: "Romania", flag: "🇷🇴" },
    { code: "+7", name: "Russia", flag: "🇷🇺" },
    { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
    { code: "+65", name: "Singapore", flag: "🇸🇬" },
    { code: "+82", name: "South Korea", flag: "🇰🇷" },
    { code: "+34", name: "Spain", flag: "🇪🇸" },
    { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
    { code: "+46", name: "Sweden", flag: "🇸🇪" },
    { code: "+41", name: "Switzerland", flag: "🇨🇭" },
    { code: "+886", name: "Taiwan", flag: "🇹🇼" },
    { code: "+66", name: "Thailand", flag: "🇹🇭" },
    { code: "+216", name: "Tunisia", flag: "🇹🇳" },
    { code: "+90", name: "Turkey", flag: "🇹🇷" },
    { code: "+380", name: "Ukraine", flag: "🇺🇦" },
    { code: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
    { code: "+84", name: "Vietnam", flag: "🇻🇳" },
    { code: "+967", name: "Yemen", flag: "🇾🇪" }
  ];
  